apiVersion: v1
kind: Service
metadata:
  name: connectznow-service
spec:
  type : NodePort
  selector:
    app: connectznow-api-and-integration-service
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8080
      name : http
      nodePort : 30000